/*------------------------------------------------------------------------
    File        : AbstractCarFactory
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   :
    Created     :
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.
USING Exercise_05.*.

INTERFACE Exercise_05.AbstractCarFactory:  
  
    /*------------------------------------------------------------------------------
     Purpose:
     Notes:
    ------------------------------------------------------------------------------*/

    METHOD PUBLIC Car createCar(  ).

END INTERFACE.