/*------------------------------------------------------------------------
  File        : OnBoardComputerHybrid
  Purpose     : 
  Syntax      : 
  Description : 
  Author(s)   :
  Created     :
  Notes       : 
----------------------------------------------------------------------*/

USING Progress.Lang.*.
USING Exercise_04.*.

BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS Exercise_04.OnBoardComputerHybrid INHERITS OnBoardComputer: 


END CLASS.