/*------------------------------------------------------------------------
  File        : Table
  Purpose     : 
  Syntax      : 
  Description : 
  Author(s)   : 
  Created     :
  Notes       : 
----------------------------------------------------------------------*/

USING Progress.Lang.*.
USING Creational.FactoryMethod.Furniture.

BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS Creational.FactoryMethod.Table INHERITS Furniture: 
END CLASS.